// Comprehensive initial mock data for CargoShare
// Strictly conforms to the backend API schema

export const INITIAL_CONTAINERS = [
  {
    id: 'CNT-88219',
    containerNumber: 'MSKU-948210-4',
    providerId: 'usr-p1',
    providerName: 'Apex Oceanic Freight Co.',
    providerStatus: 'APPROVED',
    mode: 'SEA', // SEA, RAIL, ROAD, AIR
    origin: 'Rotterdam Port (NLRTM)',
    destination: 'Jebel Ali Port, Dubai (AEJEA)',
    vesselFlightTrain: 'Vessel: CMA CGM Jacques Saadé (Voyage 241E)',
    totalCapacity: 68.0, // CBM
    availableCapacity: 24.5, // CBM
    bookedCapacity: 43.5,
    pricePerCbm: 145.0, // USD
    currency: 'USD',
    departureDate: '2026-09-28T06:00:00Z',
    arrivalDate: '2026-10-14T18:00:00Z',
    status: 'AVAILABLE', // AVAILABLE, FULL, DEPARTED, CLOSED
    matchScore: 98,
    cargoRestrictions: 'Dry goods, electronics, non-hazardous crated machinery',
    temperatureControlled: false,
    cutoffDate: '2026-09-25T12:00:00Z',
  },
  {
    id: 'CNT-77341',
    containerNumber: 'COSU-621894-0',
    providerId: 'usr-p1',
    providerName: 'Apex Oceanic Freight Co.',
    providerStatus: 'APPROVED',
    mode: 'SEA',
    origin: 'Shanghai Port (CNSHA)',
    destination: 'Hamburg Port (DEHAM)',
    vesselFlightTrain: 'Vessel: COSCO Shipping Nebula (Voyage 88B)',
    totalCapacity: 76.0,
    availableCapacity: 12.0,
    bookedCapacity: 64.0,
    pricePerCbm: 180.0,
    currency: 'USD',
    departureDate: '2026-10-02T10:00:00Z',
    arrivalDate: '2026-10-29T14:00:00Z',
    status: 'AVAILABLE',
    matchScore: 94,
    cargoRestrictions: 'FMCG, textile bails, packaged consumer retail',
    temperatureControlled: false,
    cutoffDate: '2026-09-30T17:00:00Z',
  },
  {
    id: 'CNT-55102',
    containerNumber: 'DBCA-309112-7',
    providerId: 'usr-p2',
    providerName: 'TransEurasia Rail Express',
    providerStatus: 'APPROVED',
    mode: 'RAIL',
    origin: 'Duisburg Intermodal Terminal (DEDUI)',
    destination: 'Almaty Logistic Central (KZALA)',
    vesselFlightTrain: 'Express Block Train #409-WestEast',
    totalCapacity: 58.0,
    availableCapacity: 31.0,
    bookedCapacity: 27.0,
    pricePerCbm: 210.0,
    currency: 'USD',
    departureDate: '2026-09-22T04:30:00Z',
    arrivalDate: '2026-10-01T20:00:00Z',
    status: 'AVAILABLE',
    matchScore: 89,
    cargoRestrictions: 'Industrial spare parts, automotive modules',
    temperatureControlled: true,
    cutoffDate: '2026-09-20T18:00:00Z',
  },
  {
    id: 'CNT-99034',
    containerNumber: 'INRD-118230-1',
    providerId: 'usr-p3',
    providerName: 'CrossBorder Highway Lines',
    providerStatus: 'APPROVED',
    mode: 'ROAD',
    origin: 'Antwerp Logistics Hub (BEANR)',
    destination: 'Milan Freight Depot (ITMIL)',
    vesselFlightTrain: 'Scania Heavy Rig Euro-6 #AX-991',
    totalCapacity: 42.0,
    availableCapacity: 8.5,
    bookedCapacity: 33.5,
    pricePerCbm: 85.0,
    currency: 'USD',
    departureDate: '2026-09-18T08:00:00Z',
    arrivalDate: '2026-09-20T11:00:00Z',
    status: 'AVAILABLE',
    matchScore: 86,
    cargoRestrictions: 'Palletized consumer goods',
    temperatureControlled: false,
    cutoffDate: '2026-09-17T22:00:00Z',
  },
  {
    id: 'CNT-44190',
    containerNumber: 'LHCR-882103-9',
    providerId: 'usr-p1',
    providerName: 'Apex Oceanic Freight Co.',
    providerStatus: 'APPROVED',
    mode: 'AIR',
    origin: 'Frankfurt Cargo City (FRA)',
    destination: 'Singapore Changi Airhub (SIN)',
    vesselFlightTrain: 'Boeing 777-F / LH Cargo 8402',
    totalCapacity: 35.0,
    availableCapacity: 4.2,
    bookedCapacity: 30.8,
    pricePerCbm: 640.0,
    currency: 'USD',
    departureDate: '2026-09-16T15:00:00Z',
    arrivalDate: '2026-09-17T09:30:00Z',
    status: 'AVAILABLE',
    matchScore: 78,
    cargoRestrictions: 'High-value electronics, pharmaceuticals (temp monitored)',
    temperatureControlled: true,
    cutoffDate: '2026-09-16T06:00:00Z',
  },
  {
    id: 'CNT-12093',
    containerNumber: 'MRSK-449102-3',
    providerId: 'usr-p4',
    providerName: 'Vanguard Maritime Global',
    providerStatus: 'PENDING',
    mode: 'SEA',
    origin: 'Singapore Hub (SGSIN)',
    destination: 'Nhava Sheva, Mumbai (INNSA)',
    vesselFlightTrain: 'Vessel: Maersk Mc-Kinney Moller (Voyage 02W)',
    totalCapacity: 70.0,
    availableCapacity: 70.0,
    bookedCapacity: 0.0,
    pricePerCbm: 130.0,
    currency: 'USD',
    departureDate: '2026-10-10T12:00:00Z',
    arrivalDate: '2026-10-21T06:00:00Z',
    status: 'CLOSED', // Not available until approved
    matchScore: 72,
    cargoRestrictions: 'General cargo',
    temperatureControlled: false,
    cutoffDate: '2026-10-07T12:00:00Z',
  }
];

export const INITIAL_USERS = [
  {
    id: 'usr-t1',
    name: 'Elena Rostova',
    email: 'trader@cargoshare.com',
    phone: '+49 170 8291039',
    role: 'TRADER',
    traderType: 'EXPORTER',
    company: 'Rostova Specialty Glassware GmbH',
    registeredAt: '2026-07-15T10:30:00Z',
    status: 'ACTIVE',
  },
  {
    id: 'usr-p1',
    name: 'Marcus Vance',
    email: 'provider@cargoshare.com',
    phone: '+31 10 492 8812',
    role: 'PROVIDER',
    companyName: 'Apex Oceanic Freight Co.',
    contactPerson: 'Marcus Vance',
    serviceType: 'SEA',
    operatingLocations: 'Rotterdam, Antwerp, Hamburg, Dubai, Singapore',
    routes: 'North Europe — Middle East, Trans-Pacific',
    companyDetails: 'Licensed NVOCC & vessel space consolidation specialist since 2012.',
    supportingInfo: 'IMO registration #94812, FMC License #028919.',
    providerStatus: 'APPROVED',
    registeredAt: '2026-06-10T08:00:00Z',
    status: 'ACTIVE',
  },
  {
    id: 'usr-p2',
    name: 'Dietmar Weiss',
    email: 'transeurasia@provider.com',
    phone: '+49 203 91044',
    role: 'PROVIDER',
    companyName: 'TransEurasia Rail Express',
    contactPerson: 'Dietmar Weiss',
    serviceType: 'RAIL',
    operatingLocations: 'Duisburg, Lodz, Brest, Dostyk, Almaty, Chongqing',
    routes: 'Silk Road Northern Corridor Rail Links',
    companyDetails: 'Direct block-train freight consolidation operating weekly scheduled runs.',
    supportingInfo: 'COTIF / SMGS carrier permit #EUR-RAIL-884.',
    providerStatus: 'APPROVED',
    registeredAt: '2026-07-02T11:00:00Z',
    status: 'ACTIVE',
  },
  {
    id: 'usr-p3',
    name: 'Jean-Luc Moreau',
    email: 'crossborder@provider.com',
    phone: '+32 3 294 1109',
    role: 'PROVIDER',
    companyName: 'CrossBorder Highway Lines',
    contactPerson: 'Jean-Luc Moreau',
    serviceType: 'ROAD',
    operatingLocations: 'Belgium, France, Germany, Italy, Spain',
    routes: 'Benelux to Mediterranean Corridors',
    companyDetails: 'Fleet of 85 Euro-6 semi-trailers specializing in consolidated palletized freight.',
    supportingInfo: 'EU Haulage License #BE-9948-CMR.',
    providerStatus: 'APPROVED',
    registeredAt: '2026-08-01T09:15:00Z',
    status: 'ACTIVE',
  },
  {
    id: 'usr-p4',
    name: 'Deepak Merchant',
    email: 'vanguard@applicant.com',
    phone: '+65 6834 9910',
    role: 'PROVIDER',
    companyName: 'Vanguard Maritime Global',
    contactPerson: 'Deepak Merchant',
    serviceType: 'SEA',
    operatingLocations: 'Singapore, Port Klang, Nhava Sheva, Colombo',
    routes: 'Southeast Asia to Indian Subcontinent Feeders',
    companyDetails: 'Regional feeder slot charterer consolidating SME container lots.',
    supportingInfo: 'PSA Singapore Registered Shipper #SG-PSA-44102. Audited financial statements attached.',
    providerStatus: 'PENDING',
    registeredAt: '2026-09-08T14:20:00Z',
    status: 'ACTIVE',
  },
  {
    id: 'usr-p5',
    name: 'Sarah O’Connor',
    email: 'skypacific@applicant.com',
    phone: '+44 20 7946 0991',
    role: 'PROVIDER',
    companyName: 'SkyPacific Air Consolidators',
    contactPerson: 'Sarah O’Connor',
    serviceType: 'AIR',
    operatingLocations: 'London Heathrow, Dubai World Central, Hong Kong',
    routes: 'Trans-continental Priority Air Cargo',
    companyDetails: 'Air freight forwarding charterer allocating ULD fractional capacity.',
    supportingInfo: 'IATA CASS member #08-4-8192.',
    providerStatus: 'PENDING',
    registeredAt: '2026-09-10T16:45:00Z',
    status: 'ACTIVE',
  },
  {
    id: 'usr-a1',
    name: 'Port Commander (Admin)',
    email: 'admin@cargoshare.com',
    phone: '+1 800 555 0199',
    role: 'ADMIN',
    registeredAt: '2026-01-01T00:00:00Z',
    status: 'ACTIVE',
  }
];

export const INITIAL_BOOKINGS = [
  {
    id: 'BKG-10941',
    containerId: 'CNT-88219',
    containerNumber: 'MSKU-948210-4',
    traderId: 'usr-t1',
    traderName: 'Elena Rostova',
    traderEmail: 'trader@cargoshare.com',
    traderPhone: '+49 170 8291039',
    providerId: 'usr-p1',
    providerName: 'Apex Oceanic Freight Co.',
    mode: 'SEA',
    origin: 'Rotterdam Port (NLRTM)',
    destination: 'Jebel Ali Port, Dubai (AEJEA)',
    spaceRequired: 5.5, // CBM
    pricePerCbm: 145.0,
    totalAmount: 797.5,
    currency: 'USD',
    cargoDescription: '12 Crates of Laboratory Glassware & Precision Optics',
    weightKg: 1420,
    departureDate: '2026-09-28T06:00:00Z',
    arrivalDate: '2026-10-14T18:00:00Z',
    status: 'CONFIRMED', // PENDING_PAYMENT, PAYMENT_SUCCESSFUL, CONFIRMED, IN_TRANSIT, DELIVERED, CANCELLED
    paymentStatus: 'SUCCESS',
    razorpayOrderId: 'order_CS_882910941',
    razorpayPaymentId: 'pay_CS_live_9921',
    createdAt: '2026-09-09T11:20:00Z',
    trackingNumber: 'CS-TRK-88219-01',
    timeline: [
      { step: 'PENDING_PAYMENT', title: 'Booking Initiated', timestamp: '2026-09-09T11:20:00Z', completed: true },
      { step: 'PAYMENT_SUCCESSFUL', title: 'Payment Authorized (Razorpay)', timestamp: '2026-09-09T11:24:12Z', completed: true },
      { step: 'CONFIRMED', title: 'Space Confirmed by Apex Oceanic', timestamp: '2026-09-09T12:00:00Z', completed: true },
      { step: 'IN_TRANSIT', title: 'Departed Rotterdam Berth #4', timestamp: null, completed: false },
      { step: 'DELIVERED', title: 'Customs Clearance & Hub Handover', timestamp: null, completed: false },
    ]
  },
  {
    id: 'BKG-10942',
    containerId: 'CNT-55102',
    containerNumber: 'DBCA-309112-7',
    traderId: 'usr-t1',
    traderName: 'Elena Rostova',
    traderEmail: 'trader@cargoshare.com',
    traderPhone: '+49 170 8291039',
    providerId: 'usr-p2',
    providerName: 'TransEurasia Rail Express',
    mode: 'RAIL',
    origin: 'Duisburg Intermodal Terminal (DEDUI)',
    destination: 'Almaty Logistic Central (KZALA)',
    spaceRequired: 8.0,
    pricePerCbm: 210.0,
    totalAmount: 1680.0,
    currency: 'USD',
    cargoDescription: 'Industrial CNC Stepper Motors and Sub-assemblies',
    weightKg: 2850,
    departureDate: '2026-09-22T04:30:00Z',
    arrivalDate: '2026-10-01T20:00:00Z',
    status: 'IN_TRANSIT',
    paymentStatus: 'SUCCESS',
    razorpayOrderId: 'order_CS_55102942',
    razorpayPaymentId: 'pay_CS_live_4491',
    createdAt: '2026-09-02T09:10:00Z',
    trackingNumber: 'CS-TRK-55102-02',
    timeline: [
      { step: 'PENDING_PAYMENT', title: 'Booking Initiated', timestamp: '2026-09-02T09:10:00Z', completed: true },
      { step: 'PAYMENT_SUCCESSFUL', title: 'Payment Authorized', timestamp: '2026-09-02T09:15:22Z', completed: true },
      { step: 'CONFIRMED', title: 'Container Space Allocated', timestamp: '2026-09-02T10:05:00Z', completed: true },
      { step: 'IN_TRANSIT', title: 'Train Dispatched - Crossed Poland Border', timestamp: '2026-09-05T14:30:00Z', completed: true },
      { step: 'DELIVERED', title: 'Arrived at Terminal', timestamp: null, completed: false },
    ]
  },
  {
    id: 'BKG-10943',
    containerId: 'CNT-99034',
    containerNumber: 'INRD-118230-1',
    traderId: 'usr-t1',
    traderName: 'Elena Rostova',
    traderEmail: 'trader@cargoshare.com',
    traderPhone: '+49 170 8291039',
    providerId: 'usr-p3',
    providerName: 'CrossBorder Highway Lines',
    mode: 'ROAD',
    origin: 'Antwerp Logistics Hub (BEANR)',
    destination: 'Milan Freight Depot (ITMIL)',
    spaceRequired: 3.5,
    pricePerCbm: 85.0,
    totalAmount: 297.5,
    currency: 'USD',
    cargoDescription: 'Packaged Organic Textiles',
    weightKg: 620,
    departureDate: '2026-09-18T08:00:00Z',
    arrivalDate: '2026-09-20T11:00:00Z',
    status: 'PENDING_PAYMENT',
    paymentStatus: 'CREATED',
    razorpayOrderId: 'order_CS_99034943',
    razorpayPaymentId: null,
    createdAt: '2026-09-11T16:40:00Z',
    trackingNumber: 'CS-TRK-99034-03',
    timeline: [
      { step: 'PENDING_PAYMENT', title: 'Reservation Placed (Awaiting Settlement)', timestamp: '2026-09-11T16:40:00Z', completed: true },
      { step: 'PAYMENT_SUCCESSFUL', title: 'Payment Clearance', timestamp: null, completed: false },
      { step: 'CONFIRMED', title: 'Manifest Generation', timestamp: null, completed: false },
      { step: 'IN_TRANSIT', title: 'Highway Transit', timestamp: null, completed: false },
      { step: 'DELIVERED', title: 'Depot Handover', timestamp: null, completed: false },
    ]
  },
  {
    id: 'BKG-10940',
    containerId: 'CNT-77341',
    containerNumber: 'COSU-621894-0',
    traderId: 'usr-t2',
    traderName: 'Klaus Schmidt',
    traderEmail: 'klaus@schmidt-impex.de',
    traderPhone: '+49 40 882199',
    providerId: 'usr-p1',
    providerName: 'Apex Oceanic Freight Co.',
    mode: 'SEA',
    origin: 'Shanghai Port (CNSHA)',
    destination: 'Hamburg Port (DEHAM)',
    spaceRequired: 16.0,
    pricePerCbm: 180.0,
    totalAmount: 2880.0,
    currency: 'USD',
    cargoDescription: 'Electronic Circuit Boards & Components',
    weightKg: 4100,
    departureDate: '2026-08-10T10:00:00Z',
    arrivalDate: '2026-09-06T14:00:00Z',
    status: 'DELIVERED',
    paymentStatus: 'SUCCESS',
    razorpayOrderId: 'order_CS_77341940',
    razorpayPaymentId: 'pay_CS_live_1109',
    createdAt: '2026-08-01T08:00:00Z',
    trackingNumber: 'CS-TRK-77341-00',
    timeline: [
      { step: 'PENDING_PAYMENT', title: 'Booking Initiated', timestamp: '2026-08-01T08:00:00Z', completed: true },
      { step: 'PAYMENT_SUCCESSFUL', title: 'Payment Completed', timestamp: '2026-08-01T08:12:00Z', completed: true },
      { step: 'CONFIRMED', title: 'Container Loaded', timestamp: '2026-08-05T09:00:00Z', completed: true },
      { step: 'IN_TRANSIT', title: 'Maritime Transit', timestamp: '2026-08-10T10:00:00Z', completed: true },
      { step: 'DELIVERED', title: 'Delivered Hamburg Berth 68', timestamp: '2026-09-06T14:00:00Z', completed: true },
    ]
  }
];

export const INITIAL_PAYMENTS = [
  {
    id: 'pay-001',
    bookingId: 'BKG-10941',
    traderId: 'usr-t1',
    traderName: 'Elena Rostova',
    providerId: 'usr-p1',
    amount: 797.5,
    currency: 'USD',
    razorpayOrderId: 'order_CS_882910941',
    razorpayPaymentId: 'pay_CS_live_9921',
    status: 'SUCCESS', // CREATED, SUCCESS, FAILED
    method: 'CARD (Visa ...4242)',
    createdAt: '2026-09-09T11:24:12Z',
    notes: 'Fractional Container 5.5 CBM space allocation'
  },
  {
    id: 'pay-002',
    bookingId: 'BKG-10942',
    traderId: 'usr-t1',
    traderName: 'Elena Rostova',
    providerId: 'usr-p2',
    amount: 1680.0,
    currency: 'USD',
    razorpayOrderId: 'order_CS_55102942',
    razorpayPaymentId: 'pay_CS_live_4491',
    status: 'SUCCESS',
    method: 'NET_BANKING (Deutsche Bank)',
    createdAt: '2026-09-02T09:15:22Z',
    notes: 'Rail freight 8.0 CBM space allocation'
  },
  {
    id: 'pay-003',
    bookingId: 'BKG-10943',
    traderId: 'usr-t1',
    traderName: 'Elena Rostova',
    providerId: 'usr-p3',
    amount: 297.5,
    currency: 'USD',
    razorpayOrderId: 'order_CS_99034943',
    razorpayPaymentId: null,
    status: 'CREATED',
    method: 'PENDING_AUTHORIZATION',
    createdAt: '2026-09-11T16:40:00Z',
    notes: 'Road transit 3.5 CBM space allocation'
  },
  {
    id: 'pay-004',
    bookingId: 'BKG-10940',
    traderId: 'usr-t2',
    traderName: 'Klaus Schmidt',
    providerId: 'usr-p1',
    amount: 2880.0,
    currency: 'USD',
    razorpayOrderId: 'order_CS_77341940',
    razorpayPaymentId: 'pay_CS_live_1109',
    status: 'SUCCESS',
    method: 'CARD (Mastercard ...8819)',
    createdAt: '2026-08-01T08:12:00Z',
    notes: 'Delivered container 16.0 CBM settlement'
  }
];

export const INITIAL_CHAT_MESSAGES = [
  {
    id: 'msg-1',
    threadId: 'usr-t1_usr-p1',
    bookingId: 'BKG-10941',
    containerId: 'CNT-88219',
    senderId: 'usr-t1',
    senderName: 'Elena Rostova',
    recipientId: 'usr-p1',
    content: 'Hello Marcus, we booked 5.5 CBM for glassware crates. Are standard pallet jacks adequate for uncrating at Jebel Ali depot?',
    timestamp: '2026-09-09T13:40:00Z',
    isRead: true,
  },
  {
    id: 'msg-2',
    threadId: 'usr-t1_usr-p1',
    bookingId: 'BKG-10941',
    containerId: 'CNT-88219',
    senderId: 'usr-p1',
    senderName: 'Marcus Vance (Apex Oceanic)',
    recipientId: 'usr-t1',
    content: 'Hi Elena! Yes, standard European pallets (1200x800mm) are loaded in Bay 3 with forklift ramp access. Safe packaging tags have been logged.',
    timestamp: '2026-09-09T14:05:22Z',
    isRead: true,
  },
  {
    id: 'msg-3',
    threadId: 'usr-t1_usr-p2',
    bookingId: 'BKG-10942',
    containerId: 'CNT-55102',
    senderId: 'usr-p2',
    senderName: 'Dietmar Weiss (TransEurasia)',
    recipientId: 'usr-t1',
    content: 'Express Train 409 cleared border gauge swap at Brest without hold-ups. Estimated arrival in Almaty on track.',
    timestamp: '2026-09-06T08:30:15Z',
    isRead: true,
  }
];
